name: unruffled_generator
description: Code generator for Unruffled framework.
version: 1.11.0
homepage: https://github.com/tmilian/unruffled

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  collection: ^1.16.0
  source_gen: ^1.2.2
  unruffled: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
